accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

app_name='accounts'

urlpatterns =[
    path('login/', LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', LogoutView.as_view(template_name="accounts/logout.html"), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
    #path('', RedirectView.as_view(url='/photo/', permanent=True)),
]

photo/urls.py
from django.urls import path
from .views import PhotoList, PhotoCreate, PhotoUpdate, PhotoDelete, PhotoDetail

app_name = "photo"
urlpatterns = [
    path('', PhotoList.as_view(), name='index'),
    path('detail/<int:pk>/', PhotoDetail.as_view(), name='detail'),
    path('update/<int:pk>/', PhotoUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', PhotoDelete.as_view(), name='delete'),
    path('create/', PhotoCreate.as_view(), name='create'),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='timeline_photo/%y/%m/%d')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    like = models.ManyToManyField(User, related_name='like_post', blank=True)
    favorite = models.ManyToManyField(User, related_name='favorite_post', blank=True)

    def __str__(self):
        return "text: " + self.text

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('photo:detail', args=[self.id])

accounts/views.py
from django.shortcuts import render

# Create your views here.

photo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib import messages
from .models import Photo


class PhotoList(ListView):
    model = Photo
    template_name_suffix = '_list'


class PhotoCreate(CreateView):
    model = Photo
    fields = ['text', 'image']
    template_name_suffix = '_create'
    success_url = '/'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form':form})


class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['text', 'image']
    template_name_suffix = '_update'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, "수정할 권한이 없습니다.")
            return HttpResponseRedirect('/')
        else:
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)


class PhotoDelete(DetailView):
    model = Photo
    template_name_suffix = '_delete'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, "삭제할 권한이 없습니다.")
            return HttpResponseRedirect('/')
        else:
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)

class PhotoDetail(DetailView):
    model = Photo
    template_name_suffix = '_detail'

templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <div class="alert alert-primary" role="alert">
            로그인 정보를 입력하세요.
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="로그인" class="btn btn-primary">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}
{% block title %}{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6">
        <div class="alert alert-primary" role="alert">
            로그아웃이 정상적으로 완료되었습니다.
        </div>
        <a href="{% url 'accounts:login' %}" class="btn btn-outline-success">로그인</a>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">은우이야기♥</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'photo:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'photo:create' %}">사진 업로드</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="container">
  {% if messages %}
  <div class="row">
    <div class="col"></div>
    <div class="col-6">
      {% for message in messages %}
      <div class="alert alert-{{message.tag}}">{{ message }}</div>
      {% endfor %}
    </div>
    <div class="col"></div>
  </div>
  {% endif %}
</div>
{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>

templates/photo/photo_create.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <div class="alert alert-primary" role="alert">
            모든 부분을 다 채워주세요!
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Upload" class="btn btn-primary">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/photo/photo_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-primary" role="alert">
    정말 {{object}} 를 지우실 건가요?
</div>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete OK">
</form>
{% endblock %}

templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" style="">
            <img src="{{ object.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ object.author }}</h5>
                <p class="card-text">{{ object.text }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">생성일 : {{ object.created }}</li>
                <li class="list-group-item">수정일 : {{ object.updated }}</li>
            </ul>
            <div class="card-body">
                <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>

{% endblock %}

templates/photo/photo_list.html
{% extends 'base.html' %}
{% block title %}은우이야기{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-5">
            {% for object in object_list %}

            <div class="card">
                <div class="card-header">
                    {{ object.author }}
                </div>
                <img src="{{ object.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text">{{ object.text }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">수정일 : {{ object.updated }}</li>
                    <li class="list-group-item">생성일 : {{ object.created }}</li>
                </ul>
                <div class="card-body">
                    <a href="{% url 'photo:detail' object.id %}" class="card-link">댓글달기</a>
                    {% if user == object.author %}
                    <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                    <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

templates/photo/photo_update.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}